### PR TITLE
Snsboxplot

### PR DESCRIPTION
**Pull request by lcwheeler**

### CODE REVIEW

**Comment by Zsailer** [comment]
Looks like there are some conflicts... You'll have to rebase your branch against master before we can merge.

**Comment by Zsailer** [comment]
@biophyser  Was this ready to merge?

**Comment by biophyser** [comment]
It said the conflicts were resolved. I was here and I sent it.
image

**Comment by lcwheeler** [comment]
:+1:

**Comment by Zsailer** [comment]
Sounds good. Didn't see the fix--- thought you had magical powers to merge with conflicts! ;)

**Pull request merged**
