### PR TITLE
Logos

### PR DESCRIPTION
**Pull request by lcwheeler**

### CODE REVIEW

**Comment by lcwheeler** [comment]
Hey everyone. This is just adding the remaining logos to the repo. Note that some packages i.e. LmFit and Networkx don't really have logos per se. I added the sklearn logo as a link to the sklearn home page from the advanced scientific packages page to see if it works. I can add the rest of the logo links later assuming that one works alright. Cheers!

**Comment by Zsailer** [comment]
Hey Luke,  

How are you updating your local branch? The commit logs are showing a bunch of merges from this `master` branch.

**Comment by lcwheeler** [comment]
I have been using git pull upstream master to make sure I'm up to date with this master. Then I push that to my own master. Trying to not make branches off of something that is behind the upstream master.

**Comment by Zsailer** [comment]
Are you making changes on your local master branch before you call `git pull upstream master`? These extra "merge" commits shouldn't be added... I'm just not sure why they're happening...

**Comment by lcwheeler** [comment]
No, I don't think so. My master appeared to be behind the upstream master, so I pulled from upstream to my local and then pushed to my origin master. I've done that a couple of times recently, because github listed my master as being behind upstream. Not sure what's going on.

**Comment by Zsailer** [comment]
Maybe try calling `git fetch upstream`? (You should only need to do this **one** time.) Hopefully that stops git from trying to merge upstream:master explicitly and just updates without flooding the logs.

**Comment by lcwheeler** [comment]
Okay, I just ran that. Hopefully when I push the current branch I'm working on it won't do what it's been doing. Currently adding an example seaborn histogram.

**Comment by Zsailer** [comment]
Sounds good. 👍  Sorry to be nit-picky about that--it leads to redundancy in the logs that can be annoying if we ever need to revert to an old state.

**Comment by lcwheeler** [comment]
Yeah, makes sense, no problem. Sorry for the annoying merges! Is there anything I can do right now to fix it or just avoid the issue going forward?

**Comment by Zsailer** [comment]
Try `get reset --hard <commit-id>` to got to a previous commit--the commit id you get from `git log`. That will reset your branch. Then try `git pull upstream master` to see if it still tries to merge upstream.

**Comment by Zsailer** [comment]
Note, you'll need to save the logos you added elsewhere in the meantime--`git reset` will delete anything new that was added.

**Comment by lcwheeler** [comment]
Okay, I'll give that a try later. Thanks.

**Comment by lcwheeler** [comment]
Okay, I think it is fixed on my local branch. Would it be best to just close this pull request and open a new one?

**Comment by Zsailer** [comment]
You can just **force** push to your branch. `git push origin logo -f`

**Pull request closed without merging**
