### PR TITLE
Initial plotting page

### PR DESCRIPTION
**Pull request by Zsailer**
First draft of a plotting page. 

It works for all matplotlib based plotting packages. Interactive, javascript plotting libraries are little more complicated (like altair, plotly, etc.). I'll try to attack those in a different PR. 

What do y'all think?

plotting

### CODE REVIEW

**Comment by lcwheeler** [comment]
I think it looks good. Hopefully we can all contribute to adding more examples and get that taken care of soon.

**Comment by lcwheeler** [comment]
I'm going to go ahead and merge Zach's updates to the plotting page if that's cool with everyone?

**Comment by Zsailer** [comment]
Sounds good to me. I fixed a couple typos.

**Comment by lcwheeler** [comment]
:+1:

**Pull request merged**
