### PR TITLE
add all of Joseph's mpl plots to the pages index.rst and render

### PR DESCRIPTION
**Pull request by lcwheeler**
Hey guys. Noticed that the new mpl plot additions weren't rendered, because they hadn't been added to the index.rst for the pages. This fixes it, so all the plots will show up in the gallery now.

### CODE REVIEW

**Comment by lcwheeler** [comment]
Also, just added a minor update to the seaborn boxplot example, to show how to set the axes labels directly.

**Comment by Zsailer** [comment]
Thanks! Merging.

**Comment by jharman25** [comment]
Thanks Luke!

**Comment by lcwheeler** [comment]
No problem!

**Pull request merged**
